# Wikibase with Query Service
#
# This docker-compose example can be used to pull the images from docker hub.
#
# Examples:
#
# Access Wikibase via "http://localhost:8181"
#   (or "http://$(docker-machine ip):8181" if using docker-machine)
#
# Access Query Service via "http://localhost:8282"
#   (or "http://$(docker-machine ip):8282" if using docker-machine)
version: '3'

services:
  wikibase:
    image: wikibase/wikibase:1.35-bundle
    links:
      - mysql
    ports:
     - "8181:80"
    volumes:
      - ${DATA_DIR}/mediawiki-images-data:/var/www/html/images
      - ${DATA_DIR}/quickstatements-data:/quickstatements/data
      - ./berd/LocalSettings.php.template:/LocalSettings.php.template
      - ./berd/logo_berdc_bw.jpg:/var/www/html/logo_berdc_bw.jpg
      - ./berd/TimelessTemplate.php:/var/www/html/skins/Timeless/includes/TimelessTemplate.php
      # - ./extensions/TemplateStyles:/var/www/html/extensions/TemplateStyles
    depends_on:
    - mysql
    - elasticsearch
    restart: unless-stopped
    networks:
      default:
        aliases:
         - ${CONCEPT_URI_HOST}
    environment:
      - DB_SERVER=mysql.svc:3306
      - MW_ELASTIC_HOST=elasticsearch.svc
      - MW_ELASTIC_PORT=9200
      - MW_ADMIN_NAME=${WB_ADMIN_USER}
      - MW_ADMIN_PASS=${WB_ADMIN_PASS}
      - MW_ADMIN_EMAIL=${WB_ADMIN_MAIL}
      - MW_SITE_NAME=BERD
      - MW_WG_SECRET_KEY=${WB_WG_SECRET_KEY}
      - DB_USER=berdbw
      - DB_PASS=${WB_DB_PASS}
      - DB_NAME=berdbw
      - QS_PUBLIC_SCHEME_HOST_AND_PORT=http://localhost:9191
  mysql:
    image: mariadb:10.3
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/mediawiki-mysql-data:/var/lib/mysql
      - ./berd/berd.cnf:/etc/mysql/mariadb.conf.d/berd.cnf
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: berdbw
      MYSQL_USER: berdbw
      MYSQL_PASSWORD: ${WB_DB_PASS}
    networks:
      default:
        aliases:
         - mysql.svc
    ports:
      - "127.0.0.1:63306:3306"
  wdqs-frontend:
    image: wikibase/wdqs-frontend:latest
    restart: unless-stopped
    volumes:
      - ./berd/custom-config.json:/templates/custom-config.json
    ports:
     - "8282:80"
    depends_on:
    - wdqs-proxy
    networks:
      default:
        aliases:
         - wdqs-frontend.svc
    environment:
      - BRAND_TITLE=query.BERD-BW.de
      - WIKIBASE_HOST=${CONCEPT_URI_HOST}
      - WDQS_HOST=wdqs-proxy.svc
  wdqs:
    image: wikibase/wdqs:0.3.40
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/query-service-data:/wdqs/data
    command: /runBlazegraph.sh
    networks:
      default:
        aliases:
         - wdqs.svc
    environment:
      - WIKIBASE_HOST=${CONCEPT_URI_HOST}
      - WDQS_HOST=wdqs.svc
      - WDQS_PORT=9999
      - BLAZEGRAPH_OPT=-XX:MaxRAM=4g -XX:MaxDirectMemorySize=4g -Xmx2g -Xms2g -XX:MaxPermSize=1024m -Djdk.nio.maxCachedBufferSize=1048576
      - HEAP_SIZE=2g
    expose:
      - 9999
  wdqs-proxy:
    image: wikibase/wdqs-proxy
    restart: unless-stopped
    environment:
      - PROXY_PASS_HOST=wdqs.svc:9999
    ports:
     - "8989:80"
    depends_on:
    - wdqs
    networks:
      default:
        aliases:
         - wdqs-proxy.svc
  wdqs-updater:
    image: wikibase/wdqs:0.3.40
    restart: unless-stopped
    command: /runUpdate.sh
    depends_on:
    - wdqs
    - wikibase
    networks:
      default:
        aliases:
         - wdqs-updater.svc
    environment:
     - WIKIBASE_HOST=${CONCEPT_URI_HOST}
     - WDQS_HOST=wdqs.svc
     - WDQS_PORT=9999
  elasticsearch:
    image: wikibase/elasticsearch:6.5.4-extra
    restart: unless-stopped
    networks:
      default:
        aliases:
         - elasticsearch.svc
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  quickstatements:
    image: wikibase/quickstatements:latest
    ports:
     - "9191:80"
    depends_on:
     - wikibase
    volumes:
     - ${DATA_DIR}/quickstatements-data:/quickstatements/data
    networks:
      default:
        aliases:
         - quickstatements.svc
    environment:
      - QS_PUBLIC_SCHEME_HOST_AND_PORT=http://localhost:9191
      - WB_PUBLIC_SCHEME_HOST_AND_PORT=http://localhost:8181
      - WIKIBASE_SCHEME_AND_HOST=http://${CONCEPT_URI_HOST}
      - WB_PROPERTY_NAMESPACE=122
      - "WB_PROPERTY_PREFIX=Property:"
      - WB_ITEM_NAMESPACE=120
      - "WB_ITEM_PREFIX=Item:"
