title: RaiseWikibase
description: Fast inserts into a Wikibase instance
baseurl: "/raisewikibase"
url: "https://ub-mannheim.github.io"
remote_theme: pmarsceill/just-the-docs
color_scheme: nil
search_enabled: true
aux_links:
  "View on GitHub":
    - "//github.com/UB-Mannheim/RaiseWikibase"
